# Self-study try-it activity 3.1: Running simulations in Python

NumPy, short for "Numerical Python," is a library for working with arrays and mathematical operations in Python. It is the foundation of most scientific computing in Python and is crucial for data science, engineering and research applications.

NumPy is generally more efficient than Python lists; it runs faster and uses less memory because all elements share the same data type. It supports n-dimensional arrays, which are crucial for handling complex data structures and operations. 

NumPy also provides a broad range of mathematical functions, including tools for linear algebra, statistics and random number generation.

In [3]:
#importing the library for numpy
import numpy as np

This notebook covers the different operations of the NumPy array, including:

- Creating a NumPy array

- Picking up elements from the NumPy array

- Operations in an array

- Computing the frequency of occurrence of elements in an array

- Appending elements to an array

- Creating arrays within specific intervals

- Iterating array elements

- Encoding values in an array

- Reshaping the array in different dimensions

Since this module is about probability in machine learning, most of the examples of NumPy provided in this notebook are coin or dice examples.


## Creating NumPy array

You can create NumPy arrays using the `np.array()` function.

In [7]:
# Create a one-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print("One dimensional array is" , arr1)

# Create a two-dimensional array
arr2 = np.array([[1, 2], [3, 4]])
print("Two dimensional array is", arr2)

One dimensional array is [1 2 3 4 5]
Two dimensional array is [[1 2]
 [3 4]]


### Question 1

You throw a die several times and record the outcomes: "1 - 2 - 1 - 1 - 6 - 5 - 1". Now, record the values in an array.

In [9]:
values = np.array([1,2,1,1,6,5,1])
print("The outcome of die thrown several times is given by",values)

The outcome of die thrown several times is given by [1 2 1 1 6 5 1]


## Picking up elements from a NumPy array

Elements in a NumPy array can be accessed using indexing or slicing:

- Indexing allows direct access to individual elements using their index positions. 

- Slicing enables selection of a range of elements from the array.

In [12]:
#The first element of the array is printed by using index 0
print(arr1[0])
#The last element of the array is printed by using index -1
print(arr1[-1])

1
5


In [13]:
#The index elements can be mentioned for a 2D array for selecting array elements
print(arr2[0,1])#prints the first row, second column of the array arr2

2


In [14]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements from index 1 to index (4-1)
print(arr[1:4])
# Select every second element
print(arr[::2])
# Reverse the array
print(arr[::-1])

[20 30 40]
[10 30 50]
[50 40 30 20 10]


### Question 2

Now suppose you throw a die several times and record the outcomes: "1 - 2 - 1 - 1 - 6 - 5 - 1 - 3 -4 -6 -1". Answer the following questions based on the concepts of indexing and slicing.

In [16]:
#1. What the the number of elements in the array?


In [17]:
#2.Which is the second last element in the array?


In [18]:
#3.Display the elements from index position 4 to the end of the array?


In [19]:
#4. Display the elements from the 2nd position to the 7th position in the array?



In [20]:
#5. Display the elements of the array in the reverse order?


## Operations in an array

These mathematical operations include addition, subtraction, multiplication and division of elements in arrays.

In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Addition
result_add = np.add(array1, array2)
print("The addition of array1 and array1 is ", result_add)

# Subtraction
result_subtract = np.subtract(array1, array2)
print("The result of array1 subtracted from array 2 is ",result_subtract)

# Multiplication
result_multiply = np.multiply(array1, array2)
print("The result of product of array1 and array2 is ",result_multiply)
# Division
result_divide = np.divide(array1, array2)
print("The result of array1 divided by array2 is ", result_divide)


The addition of array1 and array1 is  [5 7 9]
The result of array1 subtracted from array 2 is  [-3 -3 -3]
The result of product of array1 and array2 is  [ 4 10 18]
The result of array1 divided by array2 is  [0.25 0.4  0.5 ]


In addition to the above operations, statistical operations like sum, mean, median, mode and standard deviation can also be performed on arrays.

In [24]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate mean
mean = np.mean(arr)
print("The mean value of the array is" ,mean)

# Calculate median
median = np.median(arr)
print("The median value of the array is",median)

# Calculate standard deviation
std_dev = np.std(arr)
print("The standard deviation of the array is ",std_dev)

#Calculate sum
sum = np.sum(arr)
print("The sum of the array is ",sum)


The mean value of the array is 3.0
The median value of the array is 3.0
The standard deviation of the array is  1.4142135623730951
The sum of the array is  15


### Question 3

Imagine you throw two dice ten times and get the following readings:

- Dice 1 : 1 2 3 4 5 6 5 4 3 2

- Dice 2 : 1 1 2 2 4 5 6 3 2 1

Now, answer the following questions.

In [26]:
#1. Calculate the sum of each roll by adding corresponding elements from both arrays.


In [27]:
#2. Calculate the average reading for each die over the 10 rolls.


In [28]:
#3. Determine the median of the readings for each dice1 and dice2.


In [29]:
#4. Multiply the readings of the two dice for each roll.


In [30]:
#For a 2D array find out the mean for each row.



## Computing the frequency of occurrence of elements in an array

The frequency of occurrence of elements can be computed using `np.unique` function.

In [32]:
values = np.array([1,2,1,1,6,5,1,3,4,6,1])
unique, counts = np.unique(values, return_counts=True)
dict(zip(unique, counts))

{1: 5, 2: 1, 3: 1, 4: 1, 5: 1, 6: 2}

In [33]:
#For dice 1 what is the frequency of occurrence of every element?


In [34]:
#You suspect that dice1 is not a fair dice.
#Estimate the occurrence of each element and display the output in the form of a graph to prove your view



## Appending elements to an array

The `np.append()` function allows you to add elements to the end of an array. It does not modify the original array but returns a new array with the appended elements.

In [36]:
array3 = np.array([1,2,3])
array3 = np.append(array3, [2,4,3])
print("The appended array is ",array3)

The appended array is  [1 2 3 2 4 3]


In [37]:
#You through dice1 3 more times and get elements [2,3,3]. What is the list of numbers thrown by dice 1?


## Creating arrays within specific intervals

Use the `np.arange()` function in NumPy to create arrays with evenly spaced values within a specified interval. It is similar to the Python's `built-in range()` function. However, it works with both integers and floating-point numbers and returns a NumPy array.

The function is: `numpy.arange([start, ] stop, [step, ] dtype=None)`,

where:

- `start` is the starting value of the interval.

- `stop` is the end value of the interval.

- `step` is the spacing between values with a default 1.

- `dtype` is the data type of the output array.

In [39]:
arr_arange = np.arange(5, 10)
print("The array created is given by",arr_arange)


The array created is given by [5 6 7 8 9]


In [40]:
#List all the two-digit positive integers from 10 to 100


In [41]:
#How many numbers are there in the sequence S = 1,4,7,.....1005 for k?


## Iterating array elements

You can iterate over elements in a NumPy array using basic Python loops or specialised NumPy functions like `nditer()` and `ndenumerate()`. Let's explore each method with examples.

In [43]:
arr1_iter = np.array([1, 2, 3, 4, 5])

for element in arr:
    print(element)


1
2
3
4
5


In [44]:

arr2_iter = np.array([[1, 2, 3], [4, 5, 6]])

for row in arr2_iter:
    for element in row:
        print(element)


1
2
3
4
5
6


In [45]:
arr3_iter = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

# Iterate over each element using nditer
for element in np.nditer(arr3_iter):
    print(element)


1
2
3
4
5
6
7
8
9


In [46]:
#If both index and values are required enumerate is used
arr2_enumerate = np.array([[1, 2, 3], [4, 5, 6]])

for idx, element in np.ndenumerate(arr2_enumerate):
    print(f"Index: {idx}, Value: {element}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


In [47]:
#Suppose you have a 2D array representing the outcomes of rolling two dice multiple times.
#Each row represents a roll, and the columns represent the outcomes of the first and second dice, respectively.
#Iterate over the array and print the index and value of each outcome.
#Calculate the total sum of all dice rolls.
dice_outcomes = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [2, 5],
    [6, 3]
])


## Encoding values in an array

To encode values in a NumPy array, you can use techniques like one-hot encoding or string encoding depending on the type of data and the purpose:

- One-hot encoding is commonly used in machine learning to convert categorical data into a binary matrix.

- To encode or decode strings, use string encoding.

In [49]:
genders = np.array(['Male', 'Female', 'Male', 'Female', 'Male'])

encoded_genders = np.where(genders == 'Male', 0, 1)
# Male is encoded to 0 and Female to 1
print("Original Genders:", genders)
print("Encoded Genders:", encoded_genders)


Original Genders: ['Male' 'Female' 'Male' 'Female' 'Male']
Encoded Genders: [0 1 0 1 0]


- You record a coin-throwing experiment 10 times and obtain 'H-T-H-H-H-T-T-T-T-H'

In [51]:
#A coin is thrown 10 times and the output is noted in an array.
#Encode this information to a numeric array of '0' and '1'
#Use may use 'H' is 1, and 'T' is 0.
coin_throw = np.array(['H','T', 'H','H','H','T','T','T','T','H'])


## Reshaping the array in different dimensions

To reshape an array using NumPy, you can use the `np.reshape()` function. This function allows you to change the shape of an array without altering its data.

In [53]:
arr_reshape = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2D array with 2 rows and 3 columns
new_arr = arr_reshape.reshape(2, 3)

print(new_arr)


[[1 2 3]
 [4 5 6]]


In [54]:
# A fair coin is tossed by two players and stored in an array.
#Each player played 3 times in a row.
#Show the  values played by each player
